language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
os: linux
dist: trusty
install:
  # Install miniconda3
  - sudo apt-get update
  - sudo apt-get install build-essential
  - sudo apt-get autoremove -y
  - sudo apt-get clean
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh;
    bash Miniconda3-latest-Linux-x86_64.sh -b;
    export PATH="$HOME/miniconda3/bin:$PATH";
    rm Miniconda3-latest-Linux-x86_64.sh;
  # Create test environment with neurowriter dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - make python-deps
script:
  - make tests
after_success:
- coveralls